##########################################################
##			GENERALS			##
##########################################################
# Compiler target
CC  = cc
# Compiling flags
CFLAGS  = -Wall -Wextra -Werror
# Linking flags
LFLAGS  =
# Libraries flags
LDFLAGS =

##########################################################
##			PROJECTS			##
##########################################################
# Name
TARGET  = name
# Directorys
SRCDIR  = src
HDRDIR  = inc
OBJDIR  = obj
BINDIR  = bin
DEPDIR  = dep
DATDIR  = data
DOCDIR  = doc
TESDIR  = test

# All target variable
all:    $(TARGET)

# declaration variables
RM  = rm -f
RMDIR   = rm -rf
